### ISSUE TITLE
Make some changes on the text for exercise 1 / second.txt

### ISSUE THREAD

**Issue by vinicius5581** [vinicius5581/gitfun#10]
**Add the following paragraph to second.txt**

"Mussum Ipsum, cacilds vidis litro abertis. Per aumento de cachacis, eu reclamis. Mauris nec dolor in eros commodo tempor. Aenean aliquam molestie leo, vitae iaculis nisl. Praesent malesuada urna nisi, quis volutpat erat hendrerit non. Nam vulputate dapibus. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose."

**Comment by fernanda1411** [comment]
should I add it above or below the existem content?

**Comment by vinicius5581** [comment]
You can add it above the existing content
